import calm from '../music/calm.mp3';

export const scene_A = [
  { displayName: "Jinghua", special: null, background: null, music: null, soundEffect: null, text: "\"Hey! Are you awake?\"" },
  { displayName: null, special: null, background: null, music: null, soundEffect: null, text: "I open my eyes." },
  { displayName: null, special: null, background: "bedroom", music: calm, soundEffect: null, text: "There's a candlebra on my bedside table, which casts a weak, flickering light." },
  { displayName: null, special: null, background: null, music: null, soundEffect: null, text: "Jinghua is standing just a few feet from the side of my bed, her hands resting gently atop the handlebars of my wheelchair." },
  { displayName: "Jinghua", special: null, background: null, music: null, soundEffect: null, text: "\"We only have a few minutes. I already checked your phone and the fan in the dark room, so don't worry about those.\"" },
  { displayName: null, special: null, background: null, music: null, soundEffect: null, text: "I hoist myself up from the mattress and onto the wheelchair." },
  { displayName: null, special: null, background: null, music: null, soundEffect: null, text: "The candlelight is just strong enough to illuminate the door to the dark room, which sits ajar in the hallway to my left." },
  { displayName: null, special: null, background: null, music: null, soundEffect: null, text: "I grab my phone and the candlebra, and then place both atop my lap. The candle flame flickers, contorting the shadows along the edges of the room." },
  { displayName: "Jinghua", special: null, background: null, music: null, soundEffect: null, text: "\"Do you know what you're going to say? Assuming the ritual actually works, of course.\"" },
  { displayName: null, special: null, background: null, music: null, soundEffect: null, text: "\"Kinda? I mean ... I feel like I should just ask them outright. There's only one thing I want.\"" },
  { displayName: null, special: null, background: null, music: null, soundEffect: null, text: "I glance downwards at the empty space where my legs once stood, below the sewn flesh of my knees."},
  { displayName: null, special: null, background: "none", music: null, soundEffect: null, text: "Even now, I can still recall the pain of the impact."},
  { displayName: null, special: null, background: "forest-clearing", music: null, soundEffect: null, text: "It was a 12-meter drop from the summit to the base. The doctors said I'm lucky to even be alive."},
  { displayName: null, special: null, background: "none", music: null, soundEffect: null, text: "There's a part of me that knows I should just accept what happened to me."},
  { displayName: null, special: null, background: null, music: null, soundEffect: null, text: "If the ritual doesn't work, maybe I'll find some way to move on."},
  { displayName: null, special: null, background: "bedroom", music: null, soundEffect: null, text: "But even though I have no reason to feel so confident, I just know this'll work."},
  { displayName: null, special: null, background: null, music: null, soundEffect: null, text: "Jinghua leads me from the bedroom into the hallway."},
  { displayName: null, special: null, background: null, music: null, soundEffect: null, text: "I can already hear the whirring of the electric fan inside the dark room."},
  { displayName: null, special: null, background: null, music: null, soundEffect: null, text: "Though we draw nearer, the shadows are too thick for the light to illuminate the room's interior."},
  { displayName: null, special: null, background: null, music: null, soundEffect: null, text: "We pause at the threshold."},
  { displayName: "Jinghua", special: null, background: null, music: null, soundEffect: null, text: "\"Are you ready? Remember, you can always call me if anything goes wrong.\""},
  { displayName: null, special: null, background: "none", music: null, soundEffect: null, text: "I reply with a wordless nod. She pushes me into the dark room at exactly 3:33am."},
]
