import {jinghua, bedroom, fool_laugh, queen, fool, show_answers_xi, truth_ending} from '../dictionary'

export const truth_end = [
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "Where am I?" },
  { displayName: jinghua, special: null, background: bedroom, music: null, soundEffect: null, text: "The last thing I remember is sitting in the bedroom, waiting for the ritual to end." },
  { displayName: jinghua, special: null, background: bedroom, music: null, soundEffect: null, text: "...And getting the creepy feeling that someone was right behind me." },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "Now I'm here. Wherever this is." },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: fool_laugh, text: "..." },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: fool_laugh, text: "What the heck?" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: fool_laugh, text: "\"W-who is that? Show yourself.\"" },
  { displayName: queen, special: null, background: null, music: null, soundEffect: null, text: "\"You lack the eyes to see us, dear. But we will allow you to hear our voices.\"" },
  { displayName: queen, special: null, background: null, music: null, soundEffect: null, text: "\"We have three questions. If you wish to escape this place, you must answer honestly. First...\"" },
  { displayName: queen, special: null, background: null, music: null, soundEffect: null, text: "\"Did you truly believe this ritual would heal your friend?\"" },
  { displayName: jinghua, special: show_answers_xi, background: null, music: null, soundEffect: null, text: "\"Well ... no. Can you blame me? This was just some ritual I found on the internet.\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"And even if it did work, it seemed creepy. And dangerous. And I guess I was right...\"" },
  { displayName: fool, special: null, background: null, music: null, soundEffect: null, text: "\"You knew the risk, yet here you are. Why did you agree to help?\"" },
  { displayName: jinghua, special: show_answers_xi, background: null, music: null, soundEffect: null, text: "\"Because ... because I felt bad. Okay? I just wanted to try and make things right.\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"Hey, why are you asking me these questions, anyway?\"" },
  { displayName: queen, special: null, background: null, music: null, soundEffect: null, text: "\"Last question. Why do you feel so guilty?\"" },
  { displayName: jinghua, special: show_answers_xi, background: null, music: null, soundEffect: null, text: "\"W-wait. Wait a minute. What are you implying?\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"I don't feel guilty. I haven't done anything wrong!\"" },
  { displayName: jinghua, special: show_answers_xi, background: null, music: null, soundEffect: null, text: "\"Stop it.\"" },
  { displayName: jinghua, special: show_answers_xi, background: null, music: null, soundEffect: null, text: "\"You want me to talk about that night, don't you? The night of the accident?\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"Not calling for help isn't a crime, you know. And I thought it was a stranger who had gotten hurt.\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"I didn't realize it was my friend until it was too late!\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"If I had known, then of course I would have called for help!\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"There. You got your precious truth. So let me go, like you promised.\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"...\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"Hey! Are you still there?\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"Are you still listening?\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"Hey!\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"Let me out!\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"LET ME OUT!\"" },
  { displayName: jinghua, special: null, background: null, music: null, soundEffect: null, text: "\"LET M-\"" },
  { displayName: null, special: truth_ending, background: null, music: null, soundEffect: null, text: "" },
]
